name = "create-flight"
author = "Poodie_Poo & Rooh2os"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f33cc9cdcf89ec1bf970c11e8348a4766d43e46705795f958f7211dae400b325"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
