name: Publish Modpack
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Build CurseForge Zip
        # Forcing a static name makes the 'files' field below easier to manage
        run: packwiz curseforge export -o modpack.zip

      - name: Generate Changelog
        id: changelog
        run: |
          # Gets all commit titles from the last tag to the current commit
          echo "notes=$(git log $(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)..HEAD --pretty=format:'- %s' --no-merges)" >> $GITHUB_OUTPUT

      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: '1526879' 
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: './create-flight-*.zip'
          name: "Create Flight"
          # Use the notes generated in the previous step
          changelog: ${{ steps.changelog.outputs.notes }}
