name: Publish Modpack
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Build CurseForge Zip
        id: build
        run: |
          # Use packwiz to find the version from pack.toml
          VERSION=$(grep '^version' pack.toml | cut -d '"' -f 2)
          # Export with the specific versioned name
          packwiz curseforge export -o "create-flight-${VERSION}.zip"
          # Save the filename for the next step
          echo "filename=create-flight-${VERSION}.zip" >> $GITHUB_OUTPUT

      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: '1526879' 
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          # Use the filename we just saved in the build step
          files: "./${{ steps.build.outputs.filename }}"

          # Manually define the required metadata for a modpack
          curseforge-loaders: 'neoforge'
          curseforge-game-versions: '1.21.1'
          
          # This name will appear on the CurseForge website
          name: "create-flight-${{ steps.build.outputs.version }}.zip"
          changelog: ${{ steps.changelog.outputs.notes }}